# Cloudflare Pages Configuration
# This is a React/Vite SPA that should be deployed to Cloudflare Pages
# Cache-busting build timestamp: 2025-09-14T15:25:00Z

name = "hazlijoharnco"
compatibility_date = "2025-09-14"

# Pages configuration for SPA
pages_build_output_dir = "dist"

# Build configuration for Cloudflare Pages
[build]
command = "npm ci --ignore-scripts --no-audit --no-fund && npm run build"
cwd = "."

[build.environment_variables]
NODE_ENV = "production"
NPM_CONFIG_IGNORE_SCRIPTS = "true"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
SKIP_PREFLIGHT_CHECK = "true"
CI = "true"
GENERATE_SOURCEMAP = "false"