name = "hjc-chartered-accountants"
compatibility_date = "2024-09-14"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "./dist"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]