name = "hazlijoharnco"
compatibility_date = "2024-09-14"

[build]
command = "./build-for-cloudflare.sh"
watch_dir = "./src"

[build.environment_variables]
NODE_ENV = "production"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"

[env.production]
vars = { NODE_ENV = "production" }