// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekgglnhnitrffayubchl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZ2dsbmhuaXRyZmZheXViY2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODcxNzgsImV4cCI6MjA2MTU2MzE3OH0.QKGyTBqXBkAh1ScXzkE7R0BLMwPf61OKf8tc_8kVvQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);